#define PI 3.141592654  //円周率
#define Centerx 320     //ウィンドウの中心のx座標
#define Centery 240     //ウィンドウの中心のy座標
#define FieldLeft 20    //フィールド左端のx座標
#define FieldRight 620  //フィールド右端のx座標
#define FieldTop 20     //フィールド上端のy座標
#define FieldBottom 460 //フィールド下端のy座標
#define EnemyNumRow 5 //敵の行数
#define EnemyNumColumn 11 //敵の列数
#define EnemyBulletNum 7 //敵弾の最大数
#define LimitLine 420 //防衛ライン